from pathlib import Path
path = Path('src/tests/game_regression_tests.py')
text = path.read_text(encoding='utf-8')
# Update last-two chase test for new pacing condition (no unconditional wave>=3 rush).
text = text.replace("assert_contains(html, 'if (forceChasePlayer || dist < 70 || wave >= 3)', 'last two always chase player')", "assert_contains(html, 'if (forceChasePlayer || (data.engageDelay <= 0 && dist < data.chaseRange))', 'last two always chase while others wait for engage delay')")
insert = '''\n\ndef test_each_wave_applies_new_biome_scene():\n    assert_contains(html, 'const biomes = [', 'biome scene list')\n    assert_contains(html, "name: '沙漠'", 'desert biome')\n    assert_contains(html, "name: '森林'", 'forest biome')\n    assert_contains(html, "name: '草原'", 'grassland biome')\n    assert_contains(html, 'const biomeObjects = [];', 'biome object registry')\n    assert_contains(html, 'function applyBiomeForWave(waveNumber)', 'biome switch helper')\n    assert_contains(html, 'clearBiomeObjects();', 'old biome objects are removed')\n    assert_contains(html, 'applyBiomeForWave(wave);', 'biome applied at wave start')\n\n\ndef test_large_waves_do_not_all_rush_immediately():\n    assert_contains(html, 'engageDelay: 0,', 'dino has engage delay state')\n    assert_contains(html, 'dino.userData.engageDelay = wave >= 3 ? rand(2.5, 9.5) + i * 0.12 : rand(0.2, 2.8);', 'staggered engage delay per wave')\n    assert_contains(html, 'data.engageDelay = Math.max(0, data.engageDelay - dt);', 'engage delay counts down')\n    assert_contains(html, 'if (forceChasePlayer || (data.engageDelay <= 0 && dist < data.chaseRange))', 'chase requires delay and range except last two')\n    assert_contains(html, 'const speed = data.speed * (dist < 28 ? 1.06 : 0.88);', 'reduced chase speed')\n'''
if 'test_each_wave_applies_new_biome_scene' not in text:
    text = text.replace("\n\nif __name__ == '__main__':", insert + "\n\nif __name__ == '__main__':")
    text = text.replace('test_machine_gun_can_aim_high_for_overhead_pteranodons]', 'test_machine_gun_can_aim_high_for_overhead_pteranodons, test_each_wave_applies_new_biome_scene, test_large_waves_do_not_all_rush_immediately]')
path.write_text(text, encoding='utf-8')
