from pathlib import Path
path = Path('index.html')
text = path.read_text(encoding='utf-8')

repls = [
("    const canvas = document.getElementById('game');\n    const healthBar", "    const canvas = document.getElementById('game');\n    const crosshair = document.getElementById('crosshair');\n    const healthBar"),
("    const enemies = [];\n    const bullets = [];\n    const effects = [];", "    const enemies = [];\n    const obstacles = [];\n    const bullets = [];\n    const effects = [];\n    let aimTarget = null;"),
("      const hillMat = new THREE.MeshStandardMaterial({ color: 0x486628, roughness: 1 });\n      for (let i = 0; i < 18; i++) {\n        const hill = new THREE.Mesh(new THREE.ConeGeometry(rand(10, 24), rand(5, 14), 8), hillMat);\n        const p = randomEdgePosition(150, 245);\n        hill.position.set(p.x, hill.geometry.parameters.height / 2 - 0.3, p.z);", "      const hillMat = new THREE.MeshStandardMaterial({ color: 0x486628, roughness: 1 });\n      for (let i = 0; i < 18; i++) {\n        const hillRadius = rand(10, 24);\n        const hillHeight = rand(5, 14);\n        const hill = new THREE.Mesh(new THREE.ConeGeometry(hillRadius, hillHeight, 8), hillMat);\n        const p = randomEdgePosition(150, 245);\n        hill.position.set(p.x, hillHeight / 2 - 0.3, p.z);"),
("        hill.receiveShadow = true;\n        scene.add(hill);", "        hill.receiveShadow = true;\n        scene.add(hill);\n        registerObstacle(p.x, p.z, hillRadius * 0.82, 'hill');"),
("      scene.add(group);\n    }\n\n    function createRock", "      scene.add(group);\n      registerObstacle(x, z, 1.2 * s, 'tree');\n    }\n\n    function createRock"),
("      scene.add(rock);\n    }\n\n    const truck", "      scene.add(rock);\n      registerObstacle(x, z, 1.35 * s * Math.max(rock.scale.x, rock.scale.z), 'rock');\n    }\n\n    function registerObstacle(x, z, radius, type) {\n      obstacles.push({ x, z, radius, type });\n    }\n\n    function resolveTruckObstacleCollision(previousPosition) {\n      const truckRadius = 3.15;\n      for (const obstacle of obstacles) {\n        const dx = truck.position.x - obstacle.x;\n        const dz = truck.position.z - obstacle.z;\n        const minDistance = truckRadius + obstacle.radius;\n        if ((dx * dx + dz * dz) < minDistance * minDistance) {\n          truck.position.copy(previousPosition);\n          truck.userData.speed *= -0.18;\n          shake = Math.min(0.45, shake + 0.12);\n          return true;\n        }\n      }\n      return false;\n    }\n\n    const truck"),
("      const forward = new THREE.Vector3(0, 0, -1).applyAxisAngle(new THREE.Vector3(0, 1, 0), truck.userData.heading);\n      truck.position.addScaledVector(forward, truck.userData.speed * dt);\n      truck.position.x = THREE.MathUtils.clamp(truck.position.x, -worldSize + 8, worldSize - 8);\n      truck.position.z = THREE.MathUtils.clamp(truck.position.z, -worldSize + 8, worldSize - 8);", "      const previousPosition = truck.position.clone();\n      const forward = new THREE.Vector3(0, 0, -1).applyAxisAngle(new THREE.Vector3(0, 1, 0), truck.userData.heading);\n      truck.position.addScaledVector(forward, truck.userData.speed * dt);\n      truck.position.x = THREE.MathUtils.clamp(truck.position.x, -worldSize + 8, worldSize - 8);\n      truck.position.z = THREE.MathUtils.clamp(truck.position.z, -worldSize + 8, worldSize - 8);\n      resolveTruckObstacleCollision(previousPosition);"),
("      recoil = Math.max(0, recoil - dt * 5.5);\n    }\n\n    function getMuzzleWorldPosition", "      recoil = Math.max(0, recoil - dt * 5.5);\n      updateAimTarget();\n    }\n\n    function updateAimTarget() {\n      aimTarget = null;\n      const livingEnemies = enemies.filter(e => !e.userData.dead);\n      if (!livingEnemies.length) {\n        crosshair.style.left = '50%';\n        crosshair.style.top = '50%';\n        crosshair.style.transform = 'translate(-50%, -50%) scale(1)';\n        return;\n      }\n\n      aimRaycaster.setFromCamera(pointer, camera);\n      const hitObjects = livingEnemies.flatMap(e => e.children);\n      const directHits = aimRaycaster.intersectObjects(hitObjects, false);\n      if (directHits.length) {\n        const hit = directHits[0];\n        const dino = findEnemyRoot(hit.object);\n        if (dino) aimTarget = { dino, point: hit.point.clone(), distance: hit.distance };\n      }\n\n      if (!aimTarget) {\n        const center = new THREE.Vector2(window.innerWidth / 2, window.innerHeight / 2);\n        let best = null;\n        for (const dino of livingEnemies) {\n          const targetPoint = dino.position.clone().add(new THREE.Vector3(0, 2.1 * dino.scale.y, 0));\n          const projected = targetPoint.clone().project(camera);\n          if (projected.z < -1 || projected.z > 1) continue;\n          const screen = new THREE.Vector2((projected.x * 0.5 + 0.5) * window.innerWidth, (-projected.y * 0.5 + 0.5) * window.innerHeight);\n          const screenDistance = screen.distanceTo(center);\n          const worldDistance = camera.position.distanceTo(targetPoint);\n          if (screenDistance <= 86 && (!best || screenDistance < best.screenDistance || (screenDistance === best.screenDistance && worldDistance < best.distance))) {\n            best = { dino, point: targetPoint, screen, screenDistance, distance: worldDistance };\n          }\n        }\n        if (best) aimTarget = best;\n      }\n\n      if (aimTarget) {\n        const projected = aimTarget.point.clone().project(camera);\n        const x = (projected.x * 0.5 + 0.5) * window.innerWidth;\n        const y = (-projected.y * 0.5 + 0.5) * window.innerHeight;\n        crosshair.style.left = `${x}px`;\n        crosshair.style.top = `${y}px`;\n        crosshair.style.transform = 'translate(-50%, -50%) scale(1.25)';\n      } else {\n        crosshair.style.left = '50%';\n        crosshair.style.top = '50%';\n        crosshair.style.transform = 'translate(-50%, -50%) scale(1)';\n      }\n    }\n\n    function getMuzzleWorldPosition"),
("      aimRaycaster.setFromCamera(pointer, camera);\n      const hitObjects = enemies.filter(e => !e.userData.dead).flatMap(e => e.children);\n      const hits = aimRaycaster.intersectObjects(hitObjects, false);\n      const muzzlePos = getMuzzleWorldPosition();\n      let endPoint = muzzlePos.clone().add(aimRaycaster.ray.direction.clone().multiplyScalar(120));\n\n      if (hits.length) {\n        const hit = hits[0];\n        endPoint.copy(hit.point);\n        const dino = findEnemyRoot(hit.object);\n        if (dino && !dino.userData.dead) damageDino(dino, 18 + Math.round(Math.random() * 10), hit.point);\n      }\n      createBulletTracer(muzzlePos, endPoint);", "      updateAimTarget();\n      aimRaycaster.setFromCamera(pointer, camera);\n      const muzzlePos = getMuzzleWorldPosition();\n      let endPoint = muzzlePos.clone().add(aimRaycaster.ray.direction.clone().multiplyScalar(120));\n\n      if (aimTarget && !aimTarget.dino.userData.dead) {\n        endPoint.copy(aimTarget.point);\n        damageDino(aimTarget.dino, 18 + Math.round(Math.random() * 10), aimTarget.point);\n      } else {\n        const hitObjects = enemies.filter(e => !e.userData.dead).flatMap(e => e.children);\n        const hits = aimRaycaster.intersectObjects(hitObjects, false);\n        if (hits.length) {\n          const hit = hits[0];\n          endPoint.copy(hit.point);\n          const dino = findEnemyRoot(hit.object);\n          if (dino && !dino.userData.dead) damageDino(dino, 18 + Math.round(Math.random() * 10), hit.point);\n        }\n      }\n      createBulletTracer(muzzlePos, endPoint);")
]

for old, new in repls:
    if old not in text:
        print('MISSING PATTERN:', old[:80].replace('\n','\\n'))
    text = text.replace(old, new, 1)

path.write_text(text, encoding='utf-8')
